version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "5005:5005"

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "5004:5004"
